<a href="https://colab.research.google.com/github/oraut9859-cell/python_Basic_project/blob/main/Task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Q1. Create 2D array of shape (5, 6) filled with random numbers
arr_2d = np.random.randint(10, 101, size=(5, 6))

print("----- : Array Properties -----")
print("Generated 2D Array:\n", arr_2d)
print("\nShape of the array:", arr_2d.shape)
print("Total number of elements (size):", arr_2d.size)
print("Data type (dtype):", arr_2d.dtype)

----- : Array Properties -----
Generated 2D Array:
 [[ 20  83  69  79  29  30]
 [ 21 100  52  86  79  18]
 [ 49  79  54  57  20  78]
 [ 53  58  70  85  30  91]
 [ 74  96  87  43  73  22]]

Shape of the array: (5, 6)
Total number of elements (size): 30
Data type (dtype): int64


In [ ]:
import numpy as np

# Q2. Generate 1D array of 20 random numbers between 1 and 50
arr_1d = np.random.randint(1, 51, size=20)

print("----- Q2: Statistical Methods - Basic -----")
print("Generated 1D Array:", arr_1d)

# Minimum value and its index
min_val = np.min(arr_1d)
min_index = np.argmin(arr_1d)
print("\nMinimum value:", min_val, "at index:", min_index)

# Maximum value and its index
max_val = np.max(arr_1d)
max_index = np.argmax(arr_1d)
print("Maximum value:", max_val, "at index:", max_index)

# Sum of all elements
print("Sum of all elements:", np.sum(arr_1d))

# Mean and Standard Deviation
print("Mean:", np.mean(arr_1d))
print("Standard Deviation:", round(np.std(arr_1d), 2))

----- Q2: Statistical Methods - Basic -----
Generated 1D Array: [49 25 29 45 25 20 43 35  4 23 40 44 27  5  1 21  4 13 25 11]

Minimum value: 1 at index: 14
Maximum value: 49 at index: 0
Sum of all elements: 489
Mean: 24.45
Standard Deviation: 14.57


In [ ]:
import numpy as np

# Q3. Create 4x5 matrix of random integers between 20 and 80
matrix_4x5 = np.random.randint(20, 81, size=(4, 5))

print("----- Q3: Statistical Methods on 2D Array -----")
print("Generated 4x5 Matrix:\n", matrix_4x5)

# For entire matrix
print("\n--- Entire Matrix Stats ---")
print("Minimum value:", np.min(matrix_4x5))
print("Maximum value:", np.max(matrix_4x5))
print("Sum of all elements:", np.sum(matrix_4x5))
print("Mean:", np.mean(matrix_4x5))
print("Standard Deviation:", round(np.std(matrix_4x5), 2))

# Sum of each row and each column
print("\nSum of each row:", matrix_4x5.sum(axis=1))
print("Sum of each column:", matrix_4x5.sum(axis=0))

----- Q3: Statistical Methods on 2D Array -----
Generated 4x5 Matrix:
 [[75 58 62 36 67]
 [48 41 73 74 26]
 [78 63 76 73 53]
 [29 75 48 77 44]]

--- Entire Matrix Stats ---
Minimum value: 26
Maximum value: 78
Sum of all elements: 1176
Mean: 58.8
Standard Deviation: 16.64

Sum of each row: [298 262 343 273]
Sum of each column: [230 237 259 260 190]


In [ ]:
import numpy as np

# Q4. Create 1D array containing numbers from 1 to 24 using np.arange()
arr_1d_24 = np.arange(1, 25)

print("----- Q4: Reshape -----")
print("Original 1D Array:", arr_1d_24)
print("Shape:", arr_1d_24.shape)

# Optional: Reshape to 2D for better understanding
arr_reshaped = arr_1d_24.reshape(4, 6) # 4*6 = 24
print("Reshaped to 4x6 Array:\n", arr_reshaped)
print("New Shape:", arr_reshaped.shape)

----- Q4: Reshape -----
Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)
Reshaped to 4x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
New Shape: (4, 6)


In [ ]:
import numpy as np

# Create the given array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("----- Q5: NumPy Indexing -----")
print("Original Array:\n", arr)

# 1. Extract first row
first_row = arr[0, :] # or arr[0]
print("\n1. First row:", first_row)

# 2. Extract last column
last_column = arr[:, -1] # or arr[:, 3]
print("2. Last column:", last_column)

# 3. Extract center 2x2 submatrix
# Center elements: 60, 70, 100, 110 -> rows 1,2 and cols 1,2
center_2x2 = arr[1:3, 1:3]
print("3. Center 2x2 submatrix:\n", center_2x2)

# 4. Extract all even numbers using boolean indexing
even_numbers = arr[arr % 2 == 0]
print("4. All even numbers:", even_numbers)

----- Q5: NumPy Indexing -----
Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

1. First row: [10 20 30 40]
2. Last column: [ 40  80 120]
3. Center 2x2 submatrix:
 [[ 60  70]
 [100 110]]
4. All even numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:
import numpy as np

# Create 5x5 matrix of random integers between 1 and 100
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))

print("----- Q6: Advanced Indexing -----")
print("Original 5x5 Matrix:\n", matrix_5x5)

# 1. Print the diagonal elements
diagonal = np.diag(matrix_5x5) # or matrix_5x5.diagonal()
print("\n1. Diagonal elements:", diagonal)

# 2. Print elements greater than 50
greater_than_50 = matrix_5x5[matrix_5x5 > 50]
print("2. Elements greater than 50:", greater_than_50)

# 3. Replace all elements less than 30 with 0
matrix_5x5[matrix_5x5 < 30] = 0
print("\n3. After replacing elements < 30 with 0:")

# 4. Print the modified array
print("4. Modified Array:\n", matrix_5x5)

----- Q6: Advanced Indexing -----
Original 5x5 Matrix:
 [[65  1 37 92 13]
 [46 64 80 55 65]
 [55 25 27 29 90]
 [20 97 58 72 11]
 [44 65  7 81 25]]

1. Diagonal elements: [65 64 27 72 25]
2. Elements greater than 50: [65 92 64 80 55 65 55 90 97 58 72 65 81]

3. After replacing elements < 30 with 0:
4. Modified Array:
 [[65  0 37 92  0]
 [46 64 80 55 65]
 [55  0  0  0 90]
 [ 0 97 58 72  0]
 [44 65  0 81  0]]


In [ ]:
import numpy as np

# Create two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("----- Q7: Arithmetic Operations -----")
print("Array a:", a)
print("Array b:", b)

# Perform and print operations
print("\nAddition a + b:", a + b)
print("Subtraction a - b:", a - b)
print("Multiplication a * b:", a * b)
print("Division a / b:", a / b)

# Element-wise power (**)
print("Element-wise power a ** b:", a ** b)

# Modulo operation (%)
print("Modulo a % b:", a % b)

----- Q7: Arithmetic Operations -----
Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition a + b: [11 22 33 44]
Subtraction a - b: [ 9 18 27 36]
Multiplication a * b: [ 10  40  90 160]
Division a / b: [10. 10. 10. 10.]
Element-wise power a ** b: [     10     400   27000 2560000]
Modulo a % b: [0 0 0 0]


In [ ]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("----- Q8: Matrix Multiplication -----")
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# 1. Element-wise multiplication (*)
element_wise_mul = A * B
print("\n1. Element-wise multiplication A * B:\n", element_wise_mul)
# This multiplies corresponding elements: A[0,0]*B[0,0], A[0,1]*B[0,1], etc.

# 2. Matrix multiplication (@ or np.dot())
matrix_mul = A @ B # or np.dot(A, B)
print("\n2. Matrix multiplication A @ B:\n", matrix_mul)
# This is proper matrix multiplication: row of A dot column of B

print("\nDifference:")
print("* does element-wise multiplication of same positions")
print("@ or np.dot() does mathematical matrix multiplication using row-column rule")

----- Q8: Matrix Multiplication -----
Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

1. Element-wise multiplication A * B:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

2. Matrix multiplication A @ B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Difference:
* does element-wise multiplication of same positions
@ or np.dot() does mathematical matrix multiplication using row-column rule


In [12]:
import numpy as np

# Generate 6x6 matrix using np.random.randn() -> gives numbers from standard normal distribution
# These can be positive or negative
matrix_6x6 = np.random.randn(6, 6)

print("----- Q9: Combined Operations -----")
print("Generated 6x6 Matrix:\n", np.round(matrix_6x6, 2)) # rounded for clean display

# 1. Print shape, size, and dtype
print("\n1. Properties:")
print("Shape:", matrix_6x6.shape)
print("Size:", matrix_6x6.size)
print("Data type:", matrix_6x6.dtype)

# 2. Find index of maximum and minimum value
max_index = np.unravel_index(np.argmax(matrix_6x6), matrix_6x6.shape)
min_index = np.unravel_index(np.argmin(matrix_6x6), matrix_6x6.shape)
print("\n2. Index of max value:", max_index, "Value:", round(np.max(matrix_6x6), 2))
print("Index of min value:", min_index, "Value:", round(np.min(matrix_6x6), 2))

# 3. Extract top-left 3x3 submatrix
top_left_3x3 = matrix_6x6[:3, :3]
print("\n3. Top-left 3x3 submatrix:\n", np.round(top_left_3x3, 2))

# 4. Replace all negative numbers with their absolute value
matrix_6x6[matrix_6x6 < 0] = np.abs(matrix_6x6[matrix_6x6 < 0])
print("\n4. Matrix after replacing negatives with absolute value:\n", np.round(matrix_6x6, 2))

# 5. Print mean of modified matrix
print("\n5. Mean of modified matrix:", round(np.mean(matrix_6x6), 4))

----- Q9: Combined Operations -----
Generated 6x6 Matrix:
 [[-0.92 -0.82  1.02 -0.11  0.81  1.27]
 [-0.75 -1.09  1.09 -1.12  0.04 -0.75]
 [-0.91 -1.45  0.17  0.7   2.11 -0.9 ]
 [-1.5   2.36  2.07  0.37 -0.73  0.53]
 [-0.19 -1.65  1.28  0.14  0.84 -2.02]
 [ 0.48 -0.17  1.61 -0.68  0.07  1.23]]

1. Properties:
Shape: (6, 6)
Size: 36
Data type: float64

2. Index of max value: (np.int64(3), np.int64(1)) Value: 2.36
Index of min value: (np.int64(4), np.int64(5)) Value: -2.02

3. Top-left 3x3 submatrix:
 [[-0.92 -0.82  1.02]
 [-0.75 -1.09  1.09]
 [-0.91 -1.45  0.17]]

4. Matrix after replacing negatives with absolute value:
 [[0.92 0.82 1.02 0.11 0.81 1.27]
 [0.75 1.09 1.09 1.12 0.04 0.75]
 [0.91 1.45 0.17 0.7  2.11 0.9 ]
 [1.5  2.36 2.07 0.37 0.73 0.53]
 [0.19 1.65 1.28 0.14 0.84 2.02]
 [0.48 0.17 1.61 0.68 0.07 1.23]]

5. Mean of modified matrix: 0.9425


In [13]:
import numpy as np

print("----- Q10: Student Marks Analyzer -----")

# Student names and marks in 5 subjects
students = ['Aarav', 'Diya', 'Kabir', 'Anaya', 'Rohan']
subjects = ['Math', 'Science', 'English', 'History', 'Computer']

# 5x5 matrix: 5 students, 5 subjects. Marks 0 to 100
marks = np.array([
    [78, 85, 92, 67, 88], # Aarav
    [91, 76, 89, 82, 95], # Diya
    [65, 70, 73, 60, 68], # Kabir
    [88, 92, 85, 90, 94], # Anaya
    [72, 68, 75, 71, 70] # Rohan
])

print("Marks Table:\n", marks)

# 1. Total marks of each student
total_marks = np.sum(marks, axis=1)
print("\n1. Total Marks per Student:")
for i in range(len(students)):
    print(f"{students[i]}: {total_marks[i]}")

#

----- Q10: Student Marks Analyzer -----
Marks Table:
 [[78 85 92 67 88]
 [91 76 89 82 95]
 [65 70 73 60 68]
 [88 92 85 90 94]
 [72 68 75 71 70]]

1. Total Marks per Student:
Aarav: 410
Diya: 433
Kabir: 336
Anaya: 449
Rohan: 356
